### PR TITLE
Count aliases and images

### PR DESCRIPTION
**Pull request by loadedsith**

### CODE REVIEW

**Comment by Js41637** [comment]
This looks pretty good however I get an error while running it.

```
  if (users_by_type['Alias'][user]) {
    out += ', Aliases:' + users_by_type['Alias'][user];
  }
```
`Cannot read property 'js41637' of undefined`

**Comment by loadedsith** [comment]
Fair enough, I didn't have that case to test, this should be more robust.

**Comment by Js41637** [comment]
Was surprised to see someone go through the effort to submit a PR to some small script I made.

I decided to update the script anyway to use a table in 197909776585446a122cb4483226671f17e0307f
image

**Comment by loadedsith** [comment]
Ha! And I was very happy to see someone else had done the hard parts. :)

**Pull request merged**
